import React from 'react';
import { 
  BrainCircuit, 
  CheckCircle2, 
  HelpCircle, 
  Activity, 
  TrendingDown, 
  Layers, 
  Radio, 
  ShieldCheck,
  Zap
} from 'lucide-react';

export function ExplainableAI({ reasons }) {
  return (
    <div className="panel-card" id="panel-explainable-ai">
      <div className="flex justify-between items-center mb-3">
        <h3 className="panel-card-title !mb-0">
          <BrainCircuit className="w-4 h-4 text-cyan-400" />
          Explainable AI (XAI) - Why this recommendation?
        </h3>
        <span className="text-xs font-mono text-cyan-400 bg-cyan-950/40 px-2 py-0.5 rounded border border-cyan-500/30">
          Trace: Multi-Agent Edge Optimization
        </span>
      </div>

      <p className="text-xs text-slate-400 mb-4">
        Transparent decision logic generated by the decentralized edge coordination policy.
      </p>

      {/* List of 5 Explainable Factors */}
      <div className="xai-list">
        {reasons.map((reason, idx) => (
          <div key={reason.id} className="xai-item">
            <div className="xai-icon-box">
              <span className="font-mono font-bold text-xs">0{idx + 1}</span>
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <div className="xai-content-title font-['Chakra_Petch']">
                  {reason.title}
                </div>
                <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${
                  reason.impact === 'Critical' 
                    ? 'bg-rose-950 text-rose-400 border border-rose-800'
                    : reason.impact === 'High'
                    ? 'bg-amber-950 text-amber-400 border border-amber-800'
                    : 'bg-emerald-950 text-emerald-400 border border-emerald-800'
                }`}>
                  {reason.impact} Factor
                </span>
              </div>
              <p className="xai-content-detail mt-0.5">
                {reason.detail}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* Mathematical Constraint Objective Formulation Note */}
      <div className="mt-4 p-2.5 bg-black/40 rounded border border-slate-800/80 flex items-center justify-between text-xs font-mono text-slate-400">
        <span>Objective: min &Sigma; (w_i &middot; Delay_i + p_i &middot; Queue_i)</span>
        <span className="text-emerald-400">PCE Pareto-Optimal (0.012s solve time)</span>
      </div>
    </div>
  );
}
